;=============================================================================
; PROJECT:   XyWrite II Plus v1.10 (79,904 bytes)
; TOOLS:     MASM 3.1 / LINK 3.05 (Year: 1985)
; MZ_HEADER: Checksum=239Ah, Relocs=24
; ENTRY:     0000:01D9h
;=============================================================================
; FILE:      XY2_SEG1.ASM
; SEGMENT:   seg001 (UNK)
; ZONE:      Unknown data block 1 (128 bytes)
; LINES:     145
;=============================================================================

        INCLUDE XY2_SEGS.INC

seg001      segment byte public 'UNK'
        assume cs:seg001
        assume es:nothing, ss:nothing, ds:nothing

        db    0 ;  
        db    0 ;  
        db    0 ;  
        db    0 ;  
        db    0 ;  
        db    0 ;  
        db    0 ;  
        db    0 ;  
        db    0 ;  
        db    0 ;  
        db    0 ;  
        db    0 ;  
        db    0 ;  
        db    0 ;  
        db    0 ;  
        db    0 ;  
        db    0 ;  
        db    0 ;  
        db    0 ;  
        db    0 ;  
        db    0 ;  
        db    0 ;  
        db    0 ;  
        db    0 ;  
        db    0 ;  
        db    0 ;  
        db    0 ;  
        db    0 ;  
        db    0 ;  
        db    0 ;  
        db    0 ;  
        db    0 ;  
        db    0 ;  
        db    0 ;  
        db    0 ;  
        db    0 ;  
        db    0 ;  
        db    0 ;  
        db    0 ;  
        db    0 ;  
        db    0 ;  
        db    0 ;  
        db    0 ;  
        db    0 ;  
        db    0 ;  
        db    0 ;  
        db    0 ;  
        db    0 ;  
        db    0 ;  
        db    0 ;  
        db    0 ;  
        db    0 ;  
        db    0 ;  
        db    0 ;  
        db    0 ;  
        db    0 ;  
        db    0 ;  
        db    0 ;  
        db    0 ;  
        db    0 ;  
        db    0 ;  
        db    0 ;  
        db    0 ;  
        db    0 ;  
        db    0 ;  
        db    0 ;  
        db    0 ;  
        db    0 ;  
        db    0 ;  
        db    0 ;  
        db    0 ;  
        db    0 ;  
        db    0 ;  
        db    0 ;  
        db    0 ;  
        db    0 ;  
        db    0 ;  
        db    0 ;  
        db    0 ;  
        db    0 ;  
        db    0 ;  
        db    0 ;  
        db    0 ;  
        db    0 ;  
        db    0 ;  
        db    0 ;  
        db    0 ;  
        db    0 ;  
        db    0 ;  
        db    0 ;  
        db    0 ;  
        db    0 ;  
        db    0 ;  
        db    0 ;  
        db    0 ;  
        db    0 ;  
        db    0 ;  
        db    0 ;  
        db    0 ;  
        db    0 ;  
        db    0 ;  
        db    0 ;  
        db    0 ;  
        db    0 ;  
        db    0 ;  
        db    0 ;  
        db    0 ;  
        db    0 ;  
        db    0 ;  
        db    0 ;  
        db    0 ;  
        db    0 ;  
        db    0 ;  
        db    0 ;  
        db    0 ;  
        db    0 ;  
        db    0 ;  
        db    0 ;  
        db    0 ;  
        db    0 ;  
        db    0 ;  
        db    0 ;  
        db    0 ;  
        db    0 ;  
        db    0 ;  
        db    0 ;  
        db    0 ;  
        db    0 ;  

seg001      ends

        end
